### ISSUE TITLE
Buras granted from subjugating Karlings in campaign don't know how to build

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#149]
![2017-01-04 06-21-22](https://cloud.githubusercontent.com/assets/1813101/21628022/8ee7efb8-d235-11e6-9978-770fe199932f.png)

**Comment by Andrettin** [comment]
Thanks for reporting it! The issue was that you had developed the Teuton civilization, while those Buras are still Germanic, and the Germanic buildings are disallowed for Teuton players. This is fixed now:
https://github.com/Andrettin/Wyrmsun/commit/3d1dc0d613b9d243ecdfe8386f01cff5feb7804c
https://github.com/Andrettin/Wyrmgus/commit/14d50172c54195988e18e1c708de000ce0ab93ac
