### ISSUE TITLE
Make Resolution selection nicer

### ISSUE THREAD

**Issue by timfel** [Andrettin/Wyrmsun#15]
I've seen you have a bug where setting the game to fullscreen and selecting non-working resolution pairs doesn't work. Could this be fixed by simply combining the resolutions again (like other games do?) In war1gus I now have this, which seems to work fine. One should add more resolutions, I guess :)
```lua
menu:addLabel("Video Resolution", offx + 16, offy + top, Fonts["game"], false)
  local resolutions = {"640x400", "800x480", "1024x640", "1280x800", "1440x900", "1680x1050"}
  resolution = menu:addDropDown(resolutions, offx + 16 + 250, offy + top,
    function(dd)
	  local selected = resolutions[resolution:getSelected() + 1]
	  local x = tonumber(string.gmatch(selected, "%d+")())
	  local y = tonumber(string.gmatch(selected, "%d+$")())
	  SetVideoSize(x, y)
	  menu:stop()
	  RunOptionsMenu()
	end)
  for idx,str in ipairs(resolutions) do
    local x = tonumber(string.gmatch(str, "%d+")())
	local y = tonumber(string.gmatch(str, "%d+$")())
	print(x) print(y) print(Video.Width) print(Video.Height)
	if Video.Width == x and Video.Height == y then
	  resolution:setSelected(idx - 1)
	  break
	end
  end
```

**Comment by Andrettin** [comment]
Hey Tim, yes, that would be possible, but it would reduce the quantity of possible resolutions, unless the list became very long. But it would indeed solve the issue that you mention...

**Comment by Andrettin** [comment]
I've come up with a different solution for this: instead of recombining the resolution widths and heights, the resolution is now only changed after exiting the video options screen by pressing "OK". So now the player no longer has to exit full screen, select a resolution, and re-enter fullscreen.

This is the relevant commit:
https://github.com/Andrettin/Wyrmsun/commit/509ff7878a5ae117819538a3cab1db9598f4bab9
