### ISSUE TITLE
Update dialogues.lua

### ISSUE THREAD

**Issue by BeWorld2018** [Andrettin/Wyrmsun#161]
Some translatable strings

[dialogues.zip](https://github.com/Andrettin/Wyrmsun/files/1768997/dialogues.zip)

**Comment by BeWorld2018** [comment]
Update french language

[wyr-fr.zip](https://github.com/Andrettin/Wyrmsun/files/1769009/wyr-fr.zip)

**Comment by BeWorld2018** [comment]
Update campaign.lua for more strings translatable
[campaign.zip](https://github.com/Andrettin/Wyrmsun/files/1770811/campaign.zip)

**Comment by Andrettin** [comment]
Thank you very much! I've added the updated wyr-fr.po and campaign.lua files. For the dialogues, it isn't necessary to make those strings translatable directly, since they are already set as translatable when loaded for the dialogue window.

I've added you as a translator to the game's credits :) Thanks for your contribution!
