### ISSUE TITLE
Size of Graphics

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Andrettin/Wyrmsun#176]
Any chance of the graphics being upgraded to be larger and more high res? The buildings and units are tiny at 1080p, cannot imagine if someone tries to play it at 4k!

**Comment by Andrettin** [comment]
@DinkyDyeAussie I plan to add xBRZ (a pixel art scaling algorithm) 2x rendering at some point (or even just a 2x rendering option without a scaling algorithm).

Manually reworking all the graphics themselves to be at a higher resolution is sadly not viable, both because of the amount of graphics, and as the effort to work on pixel art increases exponentially with the resolution.

Using the xBRZ algorithm on *some* of the graphics, and then touching up the result manually is likely viable, though. So in the end we would have a mix of graphics that we just upscaled with xBRZ, and others that were upscaled and then the result was touched up manually.

Here is an example of an image upscaled 2x with the xBRZ algorithm:
![xbrz_example](https://user-images.githubusercontent.com/6322423/56710659-90aaaa00-6727-11e9-902e-b1a849a07295.png)

**Comment by DinkyDyeAussie** [comment]
That looks good. May need to sharpen the tileset graphics afterwards but it should look great of you get it implanted in the engine.

Aren't you porting it over to Godot soon?

**Comment by Andrettin** [comment]
@DinkyDyeAussie Yes, I'm currently working on that :) With the move to Godot finished, I will be able to make full use of its capabilities for improving the rendering options.

**Comment by DinkyDyeAussie** [comment]
Sounds promising. I did see the new splash screen in the main menu. Looks amazing.

I am trying to learn Godot but have only just started. I am also trying to learn Unity and Unreal Engine lol.

All these free to use engine developement environments around these days.

**Comment by Andrettin** [comment]
Thank you :) Aye, Jinn did a great job on the main menu background.

It's a great thing that general engines are so powerful nowadays, indeed, as they make development quite a bit easier. Some of the main advantages of Godot, IMO, are that it is open-source, and that it works flawlessly with version control.

**Comment by DinkyDyeAussie** [comment]
Just thinking now. You're porting your game to a new engine. Any chance of doing the same for wargus/stratagus?

**Comment by Andrettin** [comment]
@DinkyDyeAussie I wouldn't do it myself, since my goal is to further develop Wyrmsun itself, but in principle someone could adapt the Stratagus games to Wyrmgus and it would work fine, since the features of Stratagus are preserved.

I am gradually removing the Lua code, though, with the intent to completely eliminate the dependency on Lua at some point, with data being defined in .cfg files, and any necessary scripting being done in .gdscript. So the amount of adaptation to do might be non-trivial.

**Comment by Andrettin** [comment]
I would consider this issue to be fixed with the addition of the 2x scaled mode in version 4.0.0. But please feel free to reopen it if you think otherwise :)
