### ISSUE TITLE
Crash when trying to enter Game Concepts menu

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#19]
Wyrmsun b17661cf824859830eb14078965b24852e0c70b1
If you try to go to Encyclopedia -> Game Concepts, the game will fail with an assertion. 

stratagus-dbg: /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:675: virtual void gcn::Widget::setHotKey(const char*): Assertion `!"Could not parse hot key"' failed.

I've narrowed it down to the file /scripts/game_concepts.lua, where a new button seems to be created with "" (empty) hotkey. There seems to be a bug in this for-loop:
```
for game_concept_key, game_concept_value in pairsByKeys(GameConcepts) do
```

Leaving the rest to you. ;)

**Comment by Andrettin** [comment]
Thanks for the bug report :) Unfortunately I don't get such errors when playing the game with a release version on Windows, so it is very useful to get notified of them. I made it so the game no longer tries to set a hotkey to a ButtonWidget if the hotkey is empty:
https://github.com/Andrettin/Wyrmgus/commit/f20b6dcc4bd3d3a56a57498f74211e381e9fa988

Let me know if the issue was solved!

**Comment by KroArtem** [comment]
No, the problem still exists. I've recompiled Wyrmgus and updated Wyrmsun but still have the same issue.

**Comment by Andrettin** [comment]
Thanks again for the feedback :) I compiled a debug build, and managed to reproduce the error. I identified what was still causing it (it was in the Lua code), and fixed that in this commit:
https://github.com/Andrettin/Wyrmsun/commit/a8b6c1c3637d4d30ea7779943d911baa761655e7

After doing that, I got this issue no longer.
