### ISSUE TITLE
mac/linux support

### ISSUE THREAD

**Issue by koaning** [Andrettin/Wyrmsun#2]
is there any way to play this game on mac/linux? if so, is this documented? this game looks like something id love to play with.

**Comment by Andrettin** [comment]
Hey, thanks for your interest!

The Stratagus engine, which I modified for this game, supports Linux and Mac OS X, so it should be possible to get Wyrmsun working on them... although I don't think anyone has tried so far. Unfortunately, I don't am not very familiar with Linux or Mac.

If just running the executable doesn't work in those environments, you could try following these installation instruction for Stratagus:
http://stratagus.com/install.shtml

...but using Wyrmsun's modified engine source, which can be found here:
https://github.com/Andrettin/Wyrmgus

When you get the new executable, place it in the game's folder and use it instead of the old one.

**Comment by Mailaender** [comment]
It would be a lot easier from a packaging standpoint if this was a Stratagus compatible mod.

**Comment by colonist4096** [comment]
Wyrmsun is playable under wine without any compilation and it's great it's standalone

**Comment by Andrettin** [comment]
@colonist4096 Good to know :)

**Comment by koaning** [comment]
good call. the wine tip got the game running. thanks!

**Comment by Mailaender** [comment]
Wine... :disappointed:
