### ISSUE TITLE
Incorrect resources in loaded GSM

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#20]
Wyrmsun a8b6c1c3637d4d30ea7779943d911baa761655e7
As far as I understand the amount of resources (wood and stone) should be the same at the top of the screen and in the bottom (where we can sell (or whatever) them). See screenshot for more info.

![2015-10-26 14-18-31](https://cloud.githubusercontent.com/assets/1813101/10730584/f5b402a8-7c01-11e5-9fb9-d9d904b7aa7d.png)

**Comment by Andrettin** [comment]
Those are actually different values. The number at the top is the quantity stored, while the number at the bottom is the current price in gold per 100 of the resource. Now that you mention it, I do think it's not clear enough what the numbers in the town hall interface represent; I made tooltips explain them now. Thanks for the feedback!

Issue fixed in commits:
https://github.com/Andrettin/Wyrmsun/commit/e9f8e371ea7911c1b5f5f80b3e1ec57626d526c7
https://github.com/Andrettin/Wyrmgus/commit/247e3ff7d0379d105fe75f9b6a1d7e8e82d81f8b
