### ISSUE TITLE
It is possible to rewrite maps without confirmation

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#23]
Everything is said in ticket's name. Save dialogue doesn't show already created maps, so it's possible to rewrite them.

**Comment by Andrettin** [comment]
I think the editor's save map interface is a bit unclear in that sense. It looks for (and saves) the maps compressed in .gz archives. It thus doesn't actually overwrite the existing maps, because they are not in archives. For example: if, say, you write a map called "aurvang.smp" into the /maps/nidavellir/ folder, it would get saved as "aurvang.smp.gz", instead of overwriting the original "aurvang.smp" map.

To make the map saving process less confusing, I have made it so now the maps are saved directly as SMS and SMP files, instead of being saved within a GZ archive, in this commit:
https://github.com/Andrettin/Wyrmsun/commit/fff909768f201521201d261bfc8745d739849996

Thanks for the feedback :)
