### ISSUE TITLE
End Turn in GSG returns to main menu

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#34]
I'm creating GSG with the following options:
World: Random
Tactical unit multiplier: 5x
Automatic battles
The other options are by default. When the game starts I don't see my tribe and find it boring to try to locate it on the map so I pressed "End turn" and it threw me away to the main menu.

**Comment by Andrettin** [comment]
Thanks for the bug report! There was an issue with the map generation, which occurred due to the addition of claims from other factions to the Asa Tribe's home province (resulting in one of them being the owners of the province instead of the Asa). Without your faction having any provinces, the game bugged, of course. I solved this now here:
https://github.com/Andrettin/Wyrmsun/commit/f90f0caf5607d0c4062fa18eb326b6c970996315

Your help in identifying bugs is being very valuable :)

**Comment by KroArtem** [comment]
Thanks, I know it, that's why sometimes I spent time finding and narrowing bugs. :)
