### ISSUE TITLE
A Crash

### ISSUE THREAD

**Issue by Trensicourt** [Andrettin/Wyrmsun#37]
I played some custom matches and they look fun. I think it would be fun if the game becomes multiplayer. No one really plays by IP addresses. Later, I played the Earth campaign, but the game crashed when I opened the 2nd mission. Why is that? Secondly, in the first mission of the alternate campaign, I can't build infrastructure. As mentioned before, the custom missions were fun. That's because I was able to build everything. Love the music, btw.

**Comment by Andrettin** [comment]
Thanks :) Yes, it would be nice to have the game playable over multiplayer with a server. It would also be good to store things like quests completed and acquired technologies in a server, which would allow for things like achievements.

About the second Earth mission (Westward Migration), I couldn't reproduce the issue here. Are you using the latest version of the game?

In the first two Germanic missions you can't build infrastructure, because in the 1st mission you only control soldiers, and in the second mission you aren't supposed to build a base, but migrate with your workers. Similarly for the first dwarven mission, you are supposed to only gather resources in that one, instead of having to build anything.

**Comment by Trensicourt** [comment]
Thanks for the information! I'm using 1.6.1. I can't find any other version.

**Comment by Andrettin** [comment]
The latest release is 1.7.1:
https://github.com/Andrettin/Wyrmsun/releases/tag/v1.7.1
https://github.com/Andrettin/Wyrmgus/releases/tag/v1.7.1

If you're on Windows, you can download the binaries directly from the first link, but if you're on Linux you would have to build them (or wait until PlayDeb or etc. distributes a new version).

**Comment by Trensicourt** [comment]
I've installed the game and finished the first few missions. I think the early-game missions are too vulnerable to player attacks. Twice, I've won with only starting units. It's not fair for the a.i. and it feels like I'm cheating. I'm thinking of palisades, cheap wooden walls that can delay enemy attacks, but it will take some serious coding for the a.i. to make proper defenses. However, I do have another suggestion and that is the ability for your units to walk through buildings. On some custom maps, my base begins in a narrow path and often there is a road that limits building space. This causes some problems, such as walking and finding more build space.

**Comment by Andrettin** [comment]
Which missions did you win with just the initial units?

About defenses, another possibility is to add units for the AI which it will use only defensively. Palisades are a good idea (there are graphics for palisades which only need a touch-up to be used in the game). The main issue would be as you said how to make the AI properly build walls.

I think it would look weird for units to be able to pass  through buildings. Which maps did you think had too narrow a starting point?

**Comment by Trensicourt** [comment]
Sorry for not responding these past few days. Firstly, it is unfortunate that I do not remember which map I've played, so I can only give a vague response. However, I do certainly have alternatives for the unit movement, but it requires larger grids. Instead of a 4x4 for critical structures, a 5x5 is suggested. For example, a plus sign cavity is in the center of a structure. That hollow space allows for units to move through. This removes the pathing problems commonly associated with larger buildings. Then the idea of gates could be possible because if hollow buildings were to be implemented, then one-way pathing would be introduced. In addition, map generation for trees should be split into "thick" and "scattered". Scattered trees give the units movement, but still does the job of limiting vision and space. With both options, a map could have a much better variety. If this map generation and hollow buildings were both to be implemented, then pathing won't be an issue. I'd say the unit pathing would be better than games like Starcraft.

**Comment by Andrettin** [comment]
I think making the largest structures 5x5 instead of 4x4 would make them a bit too large in comparison the units, and there's also the issue that the graphics were made with them being 4x4 in mind.

The plus sign in the center of a structure as an indicator that a unit is passing through would be a good way to show that units are passing through a structure. But I'm not sure if it would really be a good thing for the gameplay to have passable structures.

I agree with you on the map generation of trees having both "thick" and "scattered" regions, as that would make the maps more diverse. I have to think of a way to implement that, though.

**Comment by Trensicourt** [comment]
Hello! I'm back again with some tweaks, especially towards the resource system. Right now, I find it really hard to maintain a war band on hard difficulty. Usually the a.i. will attack me pre-emptively while I have a weak economy. The a.i. attempts this twice and three times if I fail to defend the second time. On the other hand, when I attack I often lose a majority of my army because the a.i. is able to make large swaths of units efficiently and has many pre-built towers. This is an issue because I am unable to remake my army with what little gold I have. A temporary solution is to find another gold mine while I'm attacking to set up a base. This helps but I could never decisively annihilate them and complete the mission. Basically, I crippled my enemies infrastructure at the cost of my own economy. The a.i. that becomes crippled never invades me, which forces unfavorable battle for me. This situation becomes repetitive, so it frustrates me whenever I fail to win a hard mission. Nevertheless, I have a suggestion that benefits the player more than the a.i., that is to give Mines an accessibility variable. Gold production gets progressively lower as the depth of shaft increases, which can be measured by the amount of gold left in the mine. For example, 80% for the 1st level, 60% for the 2nd level, 40% and so on. This can only be solved either by increasing worker count or researching technology. For technology, a research could increase gold throughput through various ways. One is when a player reaches the next tech level, he/she can expand her goldmines by one level.

**Comment by Andrettin** [comment]
Hello Trensicourt, and sorry for the delay!

Which mission was that? Either way, I'm not sure if there's actually a problem there, since hard difficulty is supposed to be significantly more challenging than the normal one. On hard, the AI gets a certain amount of free resources per second, so the mines giving decreasing returns would likely make the AI stronger rather than weaker.

**Comment by Andrettin** [comment]
Closed issue as it was reported a long time ago and most likely is no longer applicable for the current state of the game.
