### ISSUE TITLE
Broken win logic in "A Rocky Home" quest

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#58]
Firstly I killed a lot of Yales, a message appeared. (like "ok, we've done with yales")
Then I collected needed amount of stone and wood, a message appeared. However, I didn't win the game. 

I had a savegame but now it seems to be not compatible with current version. However, it's not hard to check by yourself. The feature of those save was that after loading savegame a message was shown and mission was over.

**Comment by Andrettin** [comment]
Thanks for the bug report :) There was an issue which caused the player to not win the mission if they first killed the yales (instead of first collecting the resources), if the remaining yales happened to breed. I've fixed it now:
https://github.com/Andrettin/Wyrmsun/commit/d6b7cf37fae959836f8b204afa8976ebafe54890
https://github.com/Andrettin/Wyrmgus/commit/e98b137c812adb60331b47440917d0fc1c21ca30
