### ISSUE TITLE
It is not possible to remove units from towers whilst they're upgrading

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#61]
Well, the title of this ticket stands for itself.

Btw, when a unit is in a building, it's also not possible to upgrade his abilities, not sure it deserves a separate ticket.

**Comment by Andrettin** [comment]
I agree that this is not optimal, but I'm not sure what a good solution would be. Units/buildings perform their actions in turn, and a building cannot thus do an "action unload" while it is doing its "action upgrade to".

As for the level-up abilities for garrisoned units, the problem is, how to do that, interface-wise?

**Comment by KroArtem** [comment]
That's a good question for both issues. Regarding level-up abilities I can imagine the following: if a person levels up, an icon appears. When you press this icon, unit's menu is shown and you can learn this or that ability. After this menu returns to... nothing, I suppose. Or to the building  where it's sitting right now. Not sure whether it would be good from code side of view ;)

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
