### ISSUE TITLE
If a hero cannot use scrolls don't suggest him doing it

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#65]
Currently if a hero cannot use inappropriate weapons for his class (arrows for kriegers, for example) he does have only popup to drop it. Scrolls have usage popup but my krieger cannot use scrolls. I suggest having the same standard for all items.

![screenshot from 2016-01-31 19 17 17](https://cloud.githubusercontent.com/assets/1813101/12767459/5b53db7c-ca1a-11e5-9ea4-d551b82e2077.png)

**Comment by Andrettin** [comment]
The Krieger can use scrolls, it's just that this particular "spell" doesn't work for him: Detachment causes a faction-specific unit to revert to the normal civilization version of it, but your hero is already using the normal version of the unit. If you find a "Scroll of Frankish Allegiance" or a "Scroll of Suebi Allegiance", those will transform your Krieger into the respective faction-specific Kriegers.

I've made it so the "Right-click to use" no longer appears if an item can't be used because conditions don't match, though:
https://github.com/Andrettin/Wyrmgus/commit/0f29b351e8ad7909ae55df2de77450de621abb41
https://github.com/Andrettin/Wyrmsun/commit/ff5b06f94e7c51e94c9bfca04d982051550481aa
